baseurl = "http://grasskode.xyz/"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "robust"
title = "grasskode"
author = "Karan Gupta"
copyright = "Copyright (c) 2016, Karan Gupta; some rights reserved."
canonifyurls = true
paginate = 4
preserveTaxonomyNames = true

[params]
	maxPostsPerPage = 8
    disqusShortname = "grasskodexyz"
	GoogleAnalyticsUserID = "UA-73062996-1"

[taxonomies]
	category = "categories"
    tag = "tags"
    series = "series"

[[menu.main]]
	name = "Posts"
	weight = -109
	url = "/post/"
[[menu.main]]
	name = "Categories"
	weight = -108
	url = "/categories/"
[[menu.main]]
	name = "Series"
	weight = -107
	url = "/series/"
[[menu.main]]
	name = "Tags"
	weight = -106
	url = "/tags/"
[[menu.main]]
	name = "About"
	weight = -105
	url = "/about/"
